download_url: https://galaxy.ansible.com/download/cisco-iosxr-5.0.0.tar.gz
format_version: 1.0.0
name: iosxr
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 5.0.0
version_url: https://galaxy.ansible.com/api/v2/collections/cisco/iosxr/versions/5.0.0/
