download_url: https://galaxy.ansible.com/download/arubanetworks-aoscx-4.1.1.tar.gz
format_version: 1.0.0
name: aoscx
namespace: arubanetworks
server: https://galaxy.ansible.com/api/
signatures: []
version: 4.1.1
version_url: https://galaxy.ansible.com/api/v2/collections/arubanetworks/aoscx/versions/4.1.1/
